main: me.hifei.questmaster.QuestMasterPlugin
version: 1.0.0-BETA-RELEASE
name: QuestMaster
api-version: 1.20
depend:
  - CommandPanels
commands:
  start:
    description: a command
  questaction:
    description: a command