main: me.hifei.questmaster.QuestMasterPlugin
version: 1.3.0-pre1
name: QuestMaster
api-version: 1.20
depend:
  - CommandPanels
  - CrazyAdvancementAPI
commands:
  questaction:
    description: a command